### ISSUE TITLE
Remove Default Subnet

### ISSUE THREAD

**Issue by djackson-ans** [ans-coe/terraform-azurerm-virtual-network#2]
In many cases we come across, the vnet has a different address space to the subnet default value. 

We should remove the default subnet and either create no subnets (default to []) or require the entry of a subnet. 

https://github.com/ans-coe/terraform-azurerm-virtual-network/blob/fddd2b0015788f838522c2ca60dc7661b3f92dca/variables.tf#L102

**Comment by djackson-ans** [comment]
@ANS-TH @jk-ans - Invited to discuss

**Comment by djackson-ans** [comment]
default = []
default = null 
or 
leave out default entirely (not reccomended)

**Comment by tb-ans** [comment]
Default to `[]`, as this should eliminate any problems with regards to dealing with how the value is presented to the `azurerm_subnet` resource. If we were to use `null`, we'd have to use a little extra needless logic to handle that, whereas an empty list would just create the VNet and put the rest of it in the hands of the user.

**Comment by jk-ans** [comment]
Was thinking about setting the default as the first /24 in a given var.address_space 
`cidrsubnet(var.address_space, 24-split("/", var.address_space)[1])`
Spoke to @djackson-ans and went with `[]` instead
